/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AtSchema {
  status?: string;
  response?: {
    header?: {
      gtfs_realtime_version?: string;
      incrementality?: number;
      timestamp?: number;
      [k: string]: unknown;
    };
    entity?: (
      | {
          id?: string;
          is_deleted?: boolean;
          trip_update?: {
            trip?: {
              trip_id?: string;
              route_id?: string;
              direction_id?: number;
              start_time?: string;
              start_date?: string;
              schedule_relationship?: 0 | 1 | 2 | 3;
              [k: string]: unknown;
            };
            vehicle?: {
              id?: string;
              label?: string;
              license_plate?: string;
              [k: string]: unknown;
            };
            stop_time_update?: {
              stop_sequence?: number;
              stop_id?: string;
              arrival?: {
                delay?: number;
                time?: number;
                uncertainty?: number;
                [k: string]: unknown;
              };
              departure?: {
                delay?: number;
                time?: number;
                uncertainty?: number;
                [k: string]: unknown;
              };
              schedule_relationship?: 0 | 1 | 2;
              [k: string]: unknown;
            }[];
            timestamp?: number;
            delay?: number;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        }
      | {
          id?: string;
          is_deleted?: boolean;
          vehicle?: {
            trip?: {
              trip_id?: string;
              route_id?: string;
              direction_id?: number;
              start_time?: string;
              start_date?: string;
              schedule_relationship?: 0 | 1 | 2 | 3;
              [k: string]: unknown;
            };
            vehicle?: {
              id?: string;
              label?: string;
              license_plate?: string;
              [k: string]: unknown;
            };
            position?: {
              latitude?: number;
              longitude?: number;
              bearing?: number;
              odometer?: number;
              speed?: number;
              [k: string]: unknown;
            };
            timestamp?: number;
            congestion_level?: 0 | 1 | 2 | 3 | 4;
            occupancy_status?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        }
      | {
          id?: string;
          is_deleted?: boolean;
          alert?: {
            active_period?: {
              start?: number;
              end?: number;
              [k: string]: unknown;
            };
            informed_entity?: {
              agency_id?: string;
              route_id?: string;
              route_type?: number;
              trip?: {
                trip_id?: string;
                route_id?: string;
                direction_id?: number;
                start_time?: string;
                start_date?: string;
                schedule_relationship?: 0 | 1 | 2 | 3;
                [k: string]: unknown;
              };
              stop_id?: string;
              [k: string]: unknown;
            };
            cause?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
            effect?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
            url?: {
              translation?: {
                text?: string;
                language?: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            header_text?: {
              translation?: {
                text?: string;
                language?: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            description_text?: {
              translation?: {
                text?: string;
                language?: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        }
    )[];
    [k: string]: unknown;
  };
  error?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
